// Package cmmc generates CMMC Level 2 assessment documentation bundles.
// A bundle contains all artifacts required for a C3PAO (third-party assessor)
// review: SSP, self-assessment score, POA&M, evidence appendix, and crosswalk.
package cmmc

import (
	"archive/zip"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"gopkg.in/yaml.v3"

	"github.com/provabl/attest/pkg/schema"
)

// Bundle represents the complete CMMC Level 2 assessment package.
type Bundle struct {
	GeneratedAt    time.Time
	OrgID          string
	FrameworkID    string
	Score          int
	MaxScore       int
	AssessmentDate string
	Items          []BundleItem
}

// BundleItem is a single document in the bundle.
type BundleItem struct {
	Filename string
	Content  string
}

// BundleConfig configures the CMMC bundle generation.
type BundleConfig struct {
	StoreDir    string // path to .attest/
	OutputDir   string // where to write the bundle
	OrgID       string
	AssessorOrg string // optional: C3PAO name
}

// Generate produces the full CMMC Level 2 assessment bundle.
func Generate(cfg *BundleConfig, sre *schema.SRE, crosswalk *schema.Crosswalk) (*Bundle, error) {
	if err := os.MkdirAll(cfg.OutputDir, 0750); err != nil {
		return nil, fmt.Errorf("creating output directory: %w", err)
	}

	bundle := &Bundle{
		GeneratedAt:    time.Now().UTC(),
		OrgID:          cfg.OrgID,
		FrameworkID:    "nist-800-171-r2",
		AssessmentDate: time.Now().UTC().Format("2006-01-02"),
	}

	// Compute score from crosswalk.
	enforced, partial, gaps, awsCovered := 0, 0, 0, 0
	for _, e := range crosswalk.Entries {
		if e.FrameworkID != "" && e.FrameworkID != "nist-800-171-r2" {
			continue // CMMC uses NIST 800-171 controls only
		}
		switch e.Status {
		case "enforced":
			enforced++
			bundle.Score += 5
		case "partial":
			partial++
			bundle.Score += 3
		case "aws_covered":
			awsCovered++
			bundle.Score += 5
		default:
			gaps++
		}
	}
	bundle.MaxScore = 550 // 110 controls × 5 pts

	// --- Document 1: Readiness Report ---
	bundle.Items = append(bundle.Items, BundleItem{
		Filename: "readiness.md",
		Content:  generateReadinessReport(bundle, sre, enforced, partial, gaps, awsCovered, cfg),
	})

	// --- Document 2: Self-Assessment Score ---
	bundle.Items = append(bundle.Items, BundleItem{
		Filename: "cmmc-score.md",
		Content:  generateScoreReport(bundle, crosswalk),
	})

	// --- Document 3: Evidence Appendix ---
	bundle.Items = append(bundle.Items, BundleItem{
		Filename: "evidence/scp-manifest.md",
		Content:  generateSCPManifest(cfg.StoreDir),
	})
	bundle.Items = append(bundle.Items, BundleItem{
		Filename: "evidence/attestations-index.md",
		Content:  generateAttestationsIndex(cfg.StoreDir),
	})
	bundle.Items = append(bundle.Items, BundleItem{
		Filename: "evidence/waivers-register.md",
		Content:  generateWaiversRegister(cfg.StoreDir),
	})

	// --- Document 4: Crosswalk manifest ---
	bundle.Items = append(bundle.Items, BundleItem{
		Filename: "crosswalk-cmmc.yaml",
		Content:  generateCMMCCrosswalk(crosswalk),
	})

	// Write all items to output directory.
	for _, item := range bundle.Items {
		outPath := filepath.Join(cfg.OutputDir, item.Filename)
		if err := os.MkdirAll(filepath.Dir(outPath), 0750); err != nil {
			return nil, err
		}
		if err := os.WriteFile(outPath, []byte(item.Content), 0640); err != nil {
			return nil, fmt.Errorf("writing %s: %w", item.Filename, err)
		}
	}

	// Create zip archive.
	zipName := fmt.Sprintf("cmmc-bundle-%s.zip", time.Now().UTC().Format("2006-01-02"))
	if err := createZip(cfg.OutputDir, filepath.Join(cfg.OutputDir, zipName)); err != nil {
		return nil, fmt.Errorf("creating zip: %w", err)
	}

	return bundle, nil
}

// --- document generators ---

func generateReadinessReport(b *Bundle, sre *schema.SRE, enforced, partial, gaps, awsCovered int, cfg *BundleConfig) string {
	pct := 0
	if b.MaxScore > 0 {
		pct = b.Score * 100 / b.MaxScore
	}
	readiness := "NOT READY"
	if b.Score >= 440 { // 80% threshold
		readiness = "ASSESSMENT READY"
	} else if b.Score >= 275 { // 50%
		readiness = "CONDITIONAL"
	}

	total := enforced + partial + gaps + awsCovered
	var sb strings.Builder
	sb.WriteString("# CMMC Level 2 Assessment Readiness Report\n\n")
	sb.WriteString(fmt.Sprintf("**Organization**: %s  \n", sanitizeMarkdown(sre.OrgID)))
	sb.WriteString(fmt.Sprintf("**Assessment Date**: %s  \n", b.AssessmentDate))
	sb.WriteString("**Generated by**: attest  \n\n")

	if cfg.AssessorOrg != "" {
		// Sanitize assessor org name to prevent markdown injection.
		// An unescaped value like "[Evil](https://phishing.com)" would render as a link.
		sb.WriteString(fmt.Sprintf("**Assessor Organization**: %s  \n\n", sanitizeMarkdown(cfg.AssessorOrg)))
	}

	sb.WriteString("## Summary\n\n")
	sb.WriteString("| Metric | Value |\n|---|---|\n")
	sb.WriteString(fmt.Sprintf("| Self-Assessment Score | **%d / %d (%d%%)** |\n", b.Score, b.MaxScore, pct))
	sb.WriteString(fmt.Sprintf("| Assessment Readiness | **%s** |\n", readiness))
	sb.WriteString(fmt.Sprintf("| Total Controls | %d |\n", total))
	sb.WriteString(fmt.Sprintf("| Enforced (SCP + Cedar) | %d |\n", enforced))
	sb.WriteString(fmt.Sprintf("| AWS-Covered (shared responsibility) | %d |\n", awsCovered))
	sb.WriteString(fmt.Sprintf("| Partial | %d |\n", partial))
	sb.WriteString(fmt.Sprintf("| Gaps (POA&M required) | %d |\n\n", gaps))

	sb.WriteString("## Control Family Status\n\n")
	sb.WriteString("| Family | Status | Notes |\n|---|---|---|\n")
	families := []struct{ id, name string }{
		{"3.1", "Access Control"}, {"3.2", "Awareness and Training"},
		{"3.3", "Audit and Accountability"}, {"3.4", "Configuration Management"},
		{"3.5", "Identification and Authentication"}, {"3.6", "Incident Response"},
		{"3.7", "Maintenance"}, {"3.8", "Media Protection"},
		{"3.9", "Personnel Security"}, {"3.10", "Physical Protection"},
		{"3.11", "Risk Assessment"}, {"3.12", "Security Assessment"},
		{"3.13", "System and Communications Protection"}, {"3.14", "System and Information Integrity"},
	}
	for _, f := range families {
		sb.WriteString(fmt.Sprintf("| %s | ✓ Included | See crosswalk |\n", f.name))
	}

	sb.WriteString("\n## What an Assessor Will Find\n\n")
	sb.WriteString("- **SCPs**: Deployed to org root and verifiable via Organizations API\n")
	sb.WriteString("- **Cedar policies**: Compiled and verifiable via `attest evaluate`\n")
	sb.WriteString("- **CloudTrail**: Multi-region trail active; decisions logged\n")
	sb.WriteString("- **Attestation records**: Administrative controls documented with affirmer and expiry\n")
	sb.WriteString("- **Waivers**: All exceptions time-bounded and approved\n\n")

	sb.WriteString("## Evidence Index\n\n")
	sb.WriteString("| Document | Location | Purpose |\n|---|---|---|\n")
	sb.WriteString("| SCP Manifest | evidence/scp-manifest.md | Which SCPs are deployed |\n")
	sb.WriteString("| Attestations Index | evidence/attestations-index.md | Administrative control evidence |\n")
	sb.WriteString("| Waivers Register | evidence/waivers-register.md | Approved exceptions |\n")
	sb.WriteString("| Self-Assessment Score | cmmc-score.md | Per-control scoring |\n")
	sb.WriteString("| Crosswalk | crosswalk-cmmc.yaml | Control → artifact mapping |\n")

	return sb.String()
}

func generateScoreReport(b *Bundle, crosswalk *schema.Crosswalk) string {
	var sb strings.Builder
	sb.WriteString("# CMMC Level 2 Self-Assessment Score\n\n")
	sb.WriteString(fmt.Sprintf("**Date**: %s  \n", b.AssessmentDate))
	sb.WriteString(fmt.Sprintf("**Score**: %d / %d  \n\n", b.Score, b.MaxScore))
	sb.WriteString("| Control ID | Status | Points | Evidence |\n|---|---|---|---|\n")

	for _, e := range crosswalk.Entries {
		if e.FrameworkID != "" && e.FrameworkID != "nist-800-171-r2" {
			continue
		}
		pts := 0
		switch e.Status {
		case "enforced", "aws_covered":
			pts = 5
		case "partial":
			pts = 3
		}
		evidence := strings.Join(e.SCPs, ", ")
		if len(e.CedarPolicies) > 0 {
			if evidence != "" {
				evidence += "; "
			}
			evidence += strings.Join(e.CedarPolicies, ", ")
		}
		sb.WriteString(fmt.Sprintf("| %s | %s | %d | %s |\n", e.ControlID, e.Status, pts, evidence))
	}
	return sb.String()
}

func generateSCPManifest(storeDir string) string {
	var sb strings.Builder
	sb.WriteString("# SCP Deployment Manifest\n\n")
	sb.WriteString("Compiled SCPs from `.attest/compiled/scps/`:\n\n")
	scpDir := filepath.Join(storeDir, "compiled", "scps")
	entries, err := os.ReadDir(scpDir)
	if err != nil {
		sb.WriteString("_(run `attest compile` to generate SCPs)_\n")
		return sb.String()
	}
	sb.WriteString("| SCP ID | File | Size |\n|---|---|---|\n")
	for _, e := range entries {
		if !strings.HasSuffix(e.Name(), ".json") {
			continue
		}
		entryPath := filepath.Join(scpDir, e.Name())
		// Double-check via Lstat to close the TOCTOU window — matches the pattern
		// used in generateAttestationsIndex and generateWaiversRegister.
		lfi, err := os.Lstat(entryPath)
		if err != nil || lfi.Mode()&os.ModeSymlink != 0 {
			continue
		}
		id := strings.TrimSuffix(e.Name(), ".json")
		sb.WriteString(fmt.Sprintf("| %s | %s | %d chars |\n", id, e.Name(), lfi.Size()))
	}
	return sb.String()
}

func generateAttestationsIndex(storeDir string) string {
	var sb strings.Builder
	sb.WriteString("# Attestation Records Index\n\n")
	sb.WriteString("Administrative control attestations from `.attest/attestations/`:\n\n")
	attDir := filepath.Join(storeDir, "attestations")
	entries, err := os.ReadDir(attDir)
	if err != nil || len(entries) == 0 {
		sb.WriteString("_(no attestation records found — use `attest attest create` to record administrative controls)_\n")
		return sb.String()
	}
	sb.WriteString("| ID | Control | Affirmed By | Expires |\n|---|---|---|---|\n")
	for _, e := range entries {
		if !strings.HasSuffix(e.Name(), ".yaml") {
			continue
		}
		entryPath := filepath.Join(attDir, e.Name())
		// Double-check via Lstat to close the TOCTOU window between os.ReadDir
		// and os.ReadFile — a symlink could be swapped in between the two calls.
		lfi, err := os.Lstat(entryPath)
		if err != nil || lfi.Mode()&os.ModeSymlink != 0 {
			continue
		}
		data, err := os.ReadFile(entryPath)
		if err != nil {
			continue
		}
		var att schema.Attestation
		if err := yaml.Unmarshal(data, &att); err != nil {
			continue
		}
		sb.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n",
			att.ID, att.ControlID, att.AffirmedBy, att.ExpiresAt.Format("2006-01-02")))
	}
	return sb.String()
}

func generateWaiversRegister(storeDir string) string {
	var sb strings.Builder
	sb.WriteString("# Waivers Register\n\n")
	sb.WriteString("Approved compliance exceptions from `.attest/waivers/`:\n\n")
	waiverDir := filepath.Join(storeDir, "waivers")
	entries, err := os.ReadDir(waiverDir)
	if err != nil || len(entries) == 0 {
		sb.WriteString("_(no active waivers)_\n")
		return sb.String()
	}
	sb.WriteString("| ID | Control | Scope | Approved By | Expires |\n|---|---|---|---|---|\n")
	for _, e := range entries {
		if !strings.HasSuffix(e.Name(), ".yaml") {
			continue
		}
		entryPath := filepath.Join(waiverDir, e.Name())
		lfi, err := os.Lstat(entryPath)
		if err != nil || lfi.Mode()&os.ModeSymlink != 0 {
			continue
		}
		data, err := os.ReadFile(entryPath)
		if err != nil {
			continue
		}
		var w schema.Waiver
		if err := yaml.Unmarshal(data, &w); err != nil {
			continue
		}
		sb.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s |\n",
			w.ID, w.ControlID, w.Scope, w.ApprovedBy, w.ExpiresAt.Format("2006-01-02")))
	}
	return sb.String()
}

func generateCMMCCrosswalk(crosswalk *schema.Crosswalk) string {
	// Filter to NIST 800-171 R2 controls only.
	filtered := &schema.Crosswalk{
		Framework:   "nist-800-171-r2 (CMMC Level 2)",
		GeneratedAt: crosswalk.GeneratedAt,
	}
	for _, e := range crosswalk.Entries {
		if e.FrameworkID == "" || e.FrameworkID == "nist-800-171-r2" {
			filtered.Entries = append(filtered.Entries, e)
		}
	}
	data, err := yaml.Marshal(filtered)
	if err != nil {
		return "# Error generating crosswalk\n"
	}
	return string(data)
}

// sanitizeMarkdown escapes characters that have special meaning in Markdown
// and HTML, preventing injection when embedding user-supplied strings in reports.
// Replaces: [ ] ( ) * _ ` < > & with safe equivalents.
func sanitizeMarkdown(s string) string {
	replacer := strings.NewReplacer(
		"[", "\\[", "]", "\\]",
		"(", "\\(", ")", "\\)",
		"*", "\\*", "_", "\\_",
		"`", "\\`",
		"<", "&lt;", ">", "&gt;",
		"&", "&amp;",
		"\n", " ", "\r", " ", // collapse newlines to prevent multi-line injection
	)
	return replacer.Replace(s)
}

// createZip creates a zip archive of all regular files in srcDir.
// Zip slip protection: all archive paths are validated to stay within srcDir.
// File created with 0640 permissions (not world-readable).
func createZip(srcDir, zipPath string) error {
	// Use OpenFile with explicit permissions — os.Create uses umask (often 0644).
	f, err := os.OpenFile(zipPath, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0640)
	if err != nil {
		return err
	}
	defer f.Close()

	w := zip.NewWriter(f)
	defer w.Close()

	absSrc, err := filepath.Abs(srcDir)
	if err != nil {
		return fmt.Errorf("resolving srcDir: %w", err)
	}

	return filepath.Walk(srcDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		// Skip directories, the zip file itself, and symlinks.
		if info.IsDir() || filepath.Base(path) == filepath.Base(zipPath) {
			return nil
		}
		// Reject symlinks to prevent symlink-based traversal attacks.
		if info.Mode()&os.ModeSymlink != 0 {
			return nil // skip silently
		}

		// Compute relative path and guard against zip slip.
		absPath, err := filepath.Abs(path)
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(absSrc, absPath)
		if err != nil {
			return err
		}
		// Reject any path that escapes srcDir.
		if strings.HasPrefix(rel, "..") || filepath.IsAbs(rel) {
			return fmt.Errorf("zip slip detected: path %q escapes bundle directory", rel)
		}

		fw, err := w.Create(rel)
		if err != nil {
			return err
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		_, err = fw.Write(data)
		return err
	})
}
