package ssp

import (
	"fmt"
	"sort"
	"strings"
	"text/template"
	"time"
)

const sspTemplate = `# System Security Plan

**Organization (SRE)**: {{.SRE.OrgID}}{{if .SRE.Name}} — {{.SRE.Name}}{{end}}
**Framework**: {{.Framework.Name}} v{{.Framework.Version}}
**Generated**: {{.GeneratedAt.Format "January 2, 2006 15:04 MST"}}
**Overall Status**: {{.OverallStatus}}
{{- if gt .Score 0.0}}
**CMMC Score**: {{printf "%.0f" .Score}}/{{controlMax .Sections}} ({{printf "%.1f" (div .Score (controlMax .Sections) )}}%)
{{- end}}

---

## Executive Summary

This System Security Plan was automatically generated by **attest** from the live compliance
state of the AWS Organization. Every statement in this document is derived from deployed
policy artifacts, the crosswalk manifest, and evaluation evidence. No content has been
hand-written.

| Status | Count |
|--------|-------|
{{- range $status, $count := statusCounts .Sections}}
| {{title $status}} | {{$count}} |
{{- end}}

---
{{range .Sections}}
## {{.Family}}

{{range .Controls}}
### {{.ControlID}} — {{.Title}}

| | |
|---|---|
| **Status** | {{statusBadge .Status}} |
| **Assessment Score** | {{.AssessmentScore}}/5 |
| **AWS Coverage** | {{or2 .AWSCoverage "—"}} |

{{- if .CustomerImpl}}

**Implementation**: {{.CustomerImpl}}
{{- end}}

{{- if or .Enforcement.SCPs .Enforcement.CedarPolicies .Enforcement.ConfigRules}}

**Enforcement artifacts**:
{{- if .Enforcement.SCPs}}
- SCPs: {{join .Enforcement.SCPs ", "}}
{{- end}}
{{- if .Enforcement.CedarPolicies}}
- Cedar policies: {{join .Enforcement.CedarPolicies ", "}}
{{- end}}
{{- if .Enforcement.ConfigRules}}
- Config rules: {{join .Enforcement.ConfigRules ", "}}
{{- end}}
{{- end}}

{{- if .Evidence}}

**Evidence**:
{{range .Evidence}}- {{.Type}}: {{.Description}}
{{end}}
{{- end}}
{{end}}
{{end}}

---

*Generated by attest {{now}}. Source: crosswalk {{.Crosswalk.GeneratedAt.Format "2006-01-02T15:04:05Z07:00"}}.*
`

// Render converts an SSP to a markdown string.
func (s *SSP) Render() (string, error) {
	funcMap := template.FuncMap{
		"join":  strings.Join,
		"title": strings.Title, //nolint:staticcheck
		"or2": func(a, b string) string {
			if a != "" {
				return a
			}
			return b
		},
		"now": func() string {
			return time.Now().Format("2006-01-02")
		},
		"statusBadge": func(status string) string {
			switch status {
			case "Implemented":
				return "✓ Implemented"
			case "Partially Implemented":
				return "~ Partially Implemented"
			case "Not Applicable":
				return "— Not Applicable"
			default:
				return "✗ " + status
			}
		},
		"controlMax": func(sections []Section) float64 {
			count := 0
			for _, sec := range sections {
				count += len(sec.Controls)
			}
			return float64(count * 5)
		},
		"div": func(a, b float64) float64 {
			if b == 0 {
				return 0
			}
			return a / b * 100
		},
		"statusCounts": func(sections []Section) map[string]int {
			counts := make(map[string]int)
			for _, sec := range sections {
				for _, ctrl := range sec.Controls {
					counts[ctrl.Status]++
				}
			}
			return counts
		},
	}

	tmpl, err := template.New("ssp").Funcs(funcMap).Parse(sspTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing SSP template: %w", err)
	}

	// Sort sections alphabetically for deterministic output.
	sorted := make([]Section, len(s.Sections))
	copy(sorted, s.Sections)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Family < sorted[j].Family
	})

	type renderData struct {
		*SSP
		Sections []Section
	}
	data := renderData{SSP: s, Sections: sorted}

	var b strings.Builder
	if err := tmpl.Execute(&b, data); err != nil {
		return "", fmt.Errorf("rendering SSP template: %w", err)
	}
	return b.String(), nil
}
