// Package scp compiles framework control definitions into AWS Service Control Policies.
// SCPs provide structural (preventive) enforcement at the org level. Every account
// in the SRE inherits these policies — compliance by construction.
package scp

import (
	"encoding/json"
	"fmt"

	"github.com/scttfrdmn/attest/internal/framework"
	"github.com/scttfrdmn/attest/pkg/schema"
)

// IAMPolicy is the JSON structure of an SCP.
type IAMPolicy struct {
	Version   string      `json:"Version"`
	Statement []Statement `json:"Statement"`
}

// Statement is a single statement within an SCP.
type Statement struct {
	Sid       string            `json:"Sid"`
	Effect    string            `json:"Effect"`
	Action    []string          `json:"Action"`
	Resource  string            `json:"Resource"`
	Condition map[string]any    `json:"Condition,omitempty"`
}

// CompiledSCP pairs a generated SCP with its crosswalk metadata.
type CompiledSCP struct {
	ID          string                // e.g., "attest-cui-flow-restrict-01"
	Policy      IAMPolicy
	PolicyJSON  string                // serialized for deployment
	Controls    []ControlRef          // which framework controls this satisfies
	Description string
	TargetOU    string                // OU path to attach to (empty = root)
}

// ControlRef traces an SCP back to its framework control.
type ControlRef struct {
	FrameworkID string
	ControlID   string
}

// Compiler generates SCPs from a resolved control set.
type Compiler struct{}

// NewCompiler creates an SCP compiler.
func NewCompiler() *Compiler { return &Compiler{} }

// Compile generates SCPs from the resolved control set.
// Deduplicates: if HIPAA 164.312(a)(2)(iv) and NIST 800-171 3.13.11
// both require encryption at rest, one SCP is emitted satisfying both.
func (c *Compiler) Compile(rcs *framework.ResolvedControlSet) ([]CompiledSCP, error) {
	var scps []CompiledSCP

	for key, controls := range rcs.Controls {
		// Collect all structural enforcement specs across frameworks.
		var specs []schema.StructuralEnforcement
		var refs []ControlRef
		for _, rc := range controls {
			refs = append(refs, ControlRef{
				FrameworkID: rc.FrameworkID,
				ControlID:   rc.Control.ID,
			})
			specs = append(specs, rc.Control.Structural...)
		}

		if len(specs) == 0 {
			continue // No structural enforcement for this control group.
		}

		// Merge specs into a single SCP. Conservative: union of denied actions,
		// intersection of conditions (strictest wins).
		policy, err := mergeSpecs(specs)
		if err != nil {
			return nil, fmt.Errorf("compiling SCP for %s: %w", key, err)
		}

		policyJSON, err := json.MarshalIndent(policy, "", "  ")
		if err != nil {
			return nil, err
		}

		scps = append(scps, CompiledSCP{
			ID:          fmt.Sprintf("attest-%s", key),
			Policy:      *policy,
			PolicyJSON:  string(policyJSON),
			Controls:    refs,
			Description: fmt.Sprintf("Auto-generated by attest for controls: %v", refs),
		})
	}

	return scps, nil
}

// mergeSpecs combines multiple structural enforcement specs into one SCP.
func mergeSpecs(specs []schema.StructuralEnforcement) (*IAMPolicy, error) {
	policy := &IAMPolicy{Version: "2012-10-17"}

	for _, spec := range specs {
		stmt := Statement{
			Sid:    spec.ID,
			Effect: spec.Effect,
			Action: spec.Actions,
			Resource: "*",
		}
		// TODO: Parse conditions from spec and add to statement.
		policy.Statement = append(policy.Statement, stmt)
	}
	return policy, nil
}
