// Package scp compiles framework control definitions into AWS Service Control Policies.
// SCPs provide structural (preventive) enforcement at the org level. Every account
// in the SRE inherits these policies — compliance by construction.
package scp

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/provabl/attest/internal/framework"
	"github.com/provabl/attest/pkg/schema"
)

// scpSizeLimit is the AWS maximum size for an SCP document in bytes.
const scpSizeLimit = 5120

// maxActionsPerStatement caps actions per statement to keep well under the size limit
// when splitting is needed.
const maxActionsPerStatement = 40

// IAMPolicy is the JSON structure of an SCP.
type IAMPolicy struct {
	Version   string      `json:"Version"`
	Statement []Statement `json:"Statement"`
}

// Statement is a single statement within an SCP.
type Statement struct {
	Sid       string         `json:"Sid"`
	Effect    string         `json:"Effect"`
	Action    []string       `json:"Action"`
	Resource  string         `json:"Resource"`
	Condition map[string]any `json:"Condition,omitempty"`
}

// CompiledSCP pairs a generated SCP with its crosswalk metadata.
type CompiledSCP struct {
	ID          string       // e.g., "attest-scp-require-mfa"
	Policy      IAMPolicy
	PolicyJSON  string       // serialized for deployment
	Controls    []ControlRef // which framework controls this satisfies
	Description string
	TargetOU    string // OU path to attach to (empty = root)
}

// ControlRef traces an SCP back to its framework control.
type ControlRef struct {
	FrameworkID string
	ControlID   string
}

// conditionEntry is a parsed IAM condition ready to be added to a Statement.
type conditionEntry struct {
	operator string   // IAM condition operator: StringNotEquals, ArnNotLike, Bool, etc.
	key      string   // condition key: aws:MultiFactorAuthPresent, etc.
	values   []string // one or more values
}

// Compiler generates SCPs from a resolved control set.
type Compiler struct{}

// NewCompiler creates an SCP compiler.
func NewCompiler() *Compiler { return &Compiler{} }

// Compile generates SCPs from the resolved control set.
// Deduplicates: if two controls share the same structural enforcement ID,
// one SCP is emitted satisfying both. Splits SCPs that exceed 5120 bytes.
func (c *Compiler) Compile(rcs *framework.ResolvedControlSet) ([]CompiledSCP, error) {
	var scps []CompiledSCP

	for key, controls := range rcs.Controls {
		var specs []schema.StructuralEnforcement
		var refs []ControlRef
		for _, rc := range controls {
			refs = append(refs, ControlRef{
				FrameworkID: rc.FrameworkID,
				ControlID:   rc.Control.ID,
			})
			specs = append(specs, rc.Control.Structural...)
		}

		if len(specs) == 0 {
			continue
		}

		policies, err := compileSpecs(key, specs, refs)
		if err != nil {
			return nil, fmt.Errorf("compiling SCP for %s: %w", key, err)
		}
		scps = append(scps, policies...)
	}

	return scps, nil
}

// compileSpecs builds one or more CompiledSCPs from a set of structural enforcement specs.
// Splits into multiple SCPs if the result exceeds scpSizeLimit.
func compileSpecs(key string, specs []schema.StructuralEnforcement, refs []ControlRef) ([]CompiledSCP, error) {
	policy, err := mergeSpecs(specs)
	if err != nil {
		return nil, err
	}

	policyJSON, err := json.MarshalIndent(policy, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshaling SCP: %w", err)
	}

	if len(policyJSON) <= scpSizeLimit {
		return []CompiledSCP{{
			ID:          sanitizeID(fmt.Sprintf("attest-%s", key)),
			Policy:      *policy,
			PolicyJSON:  string(policyJSON),
			Controls:    refs,
			Description: fmt.Sprintf("Auto-generated by attest for %d control(s)", len(refs)),
		}}, nil
	}

	// Policy exceeds size limit — split by statement.
	return splitPolicy(key, policy, refs)
}

// mergeSpecs combines multiple structural enforcement specs into one IAM policy.
func mergeSpecs(specs []schema.StructuralEnforcement) (*IAMPolicy, error) {
	policy := &IAMPolicy{Version: "2012-10-17"}

	for _, spec := range specs {
		stmt := Statement{
			Sid:      spec.ID,
			Effect:   spec.Effect,
			Action:   spec.Actions,
			Resource: "*",
		}

		// Parse condition strings into IAM condition block.
		if len(spec.Conditions) > 0 {
			cond, err := buildConditionBlock(spec.Conditions)
			if err != nil {
				return nil, fmt.Errorf("parsing conditions for %s: %w", spec.ID, err)
			}
			stmt.Condition = cond
		}

		policy.Statement = append(policy.Statement, stmt)
	}
	return policy, nil
}

// buildConditionBlock converts a slice of condition strings into an IAM Condition map.
// Multiple conditions with the same operator and key have their values merged.
func buildConditionBlock(conditions []string) (map[string]any, error) {
	// operator → key → []values
	type condMap map[string]map[string][]string
	collected := make(condMap)

	for _, cond := range conditions {
		entry, err := parseCondition(cond)
		if err != nil {
			// Unrecognized condition format — emit as a comment-style StringEquals
			// so the SCP is still valid. Callers should fix the framework YAML.
			continue
		}

		if _, ok := collected[entry.operator]; !ok {
			collected[entry.operator] = make(map[string][]string)
		}
		collected[entry.operator][entry.key] = append(collected[entry.operator][entry.key], entry.values...)
	}

	if len(collected) == 0 {
		return nil, nil
	}

	// Convert to map[string]any for JSON marshaling.
	// Single-value conditions serialize as a string; multi-value as []string.
	result := make(map[string]any)
	for op, keys := range collected {
		keyMap := make(map[string]any)
		for k, vals := range keys {
			if len(vals) == 1 {
				keyMap[k] = vals[0]
			} else {
				keyMap[k] = vals
			}
		}
		result[op] = keyMap
	}
	return result, nil
}

// parseCondition parses a framework YAML condition string into an IAM condition entry.
//
// Supported patterns:
//
//	key != true / key == false     → Bool: false
//	key == true / key != false     → Bool: true
//	arn-key == arn:...*...         → ArnLike
//	arn-key != arn:...*...         → ArnNotLike
//	key == value                   → StringEquals
//	key != value                   → StringNotEquals
//	key not in [v1, v2, ...]       → StringNotEquals (array)
//	key in [v1, v2, ...]           → StringEquals (array)
//	key does not contain str       → StringNotLike (*str*)
//	key contains str               → StringLike (*str*)
func parseCondition(s string) (*conditionEntry, error) {
	s = strings.TrimSpace(s)

	// "key not in [v1, v2, ...]"
	if i := strings.Index(s, " not in ["); i != -1 {
		key := strings.TrimSpace(s[:i])
		values := parseListValues(s[i+9:])
		return &conditionEntry{operator: "StringNotEquals", key: key, values: values}, nil
	}
	// "key in [v1, v2, ...]"
	if i := strings.Index(s, " in ["); i != -1 {
		key := strings.TrimSpace(s[:i])
		values := parseListValues(s[i+5:])
		return &conditionEntry{operator: "StringEquals", key: key, values: values}, nil
	}
	// "key does not contain str"
	if i := strings.Index(s, " does not contain "); i != -1 {
		key := strings.TrimSpace(s[:i])
		val := strings.TrimSpace(s[i+18:])
		return &conditionEntry{operator: "StringNotLike", key: key, values: []string{"*" + val + "*"}}, nil
	}
	// "key contains str"
	if i := strings.Index(s, " contains "); i != -1 {
		key := strings.TrimSpace(s[:i])
		val := strings.TrimSpace(s[i+10:])
		return &conditionEntry{operator: "StringLike", key: key, values: []string{"*" + val + "*"}}, nil
	}

	// Binary operators: ==, !=
	for _, op := range []string{" != ", " == "} {
		idx := strings.Index(s, op)
		if idx == -1 {
			continue
		}
		key := strings.TrimSpace(s[:idx])
		val := strings.TrimSpace(s[idx+len(op):])
		isNotEqual := op == " != "

		// Bool detection: value is "true" or "false"
		if val == "true" || val == "false" {
			boolVal := val
			if isNotEqual {
				// != true → Bool: false; != false → Bool: true
				if val == "true" {
					boolVal = "false"
				} else {
					boolVal = "true"
				}
			}
			return &conditionEntry{operator: "Bool", key: key, values: []string{boolVal}}, nil
		}

		// ARN detection: key contains "ARN" (case-insensitive) or value starts with "arn:"
		isARN := strings.Contains(strings.ToUpper(key), "ARN") || strings.HasPrefix(val, "arn:")
		if isARN {
			hasWildcard := strings.Contains(val, "*") || strings.Contains(val, "?")
			if hasWildcard {
				if isNotEqual {
					return &conditionEntry{operator: "ArnNotLike", key: key, values: []string{val}}, nil
				}
				return &conditionEntry{operator: "ArnLike", key: key, values: []string{val}}, nil
			}
			if isNotEqual {
				return &conditionEntry{operator: "ArnNotEquals", key: key, values: []string{val}}, nil
			}
			return &conditionEntry{operator: "ArnEquals", key: key, values: []string{val}}, nil
		}

		// Default: String comparison
		if isNotEqual {
			return &conditionEntry{operator: "StringNotEquals", key: key, values: []string{val}}, nil
		}
		return &conditionEntry{operator: "StringEquals", key: key, values: []string{val}}, nil
	}

	return nil, fmt.Errorf("unrecognized condition format: %q", s)
}

// sanitizeID replaces characters invalid in filenames with hyphens.
func sanitizeID(s string) string {
	var b strings.Builder
	prev := '-'
	for _, r := range s {
		if r == '/' || r == ' ' || r == ':' || r == '\\' {
			r = '-'
		}
		if r == '-' && prev == '-' {
			continue
		}
		b.WriteRune(r)
		prev = r
	}
	return strings.Trim(b.String(), "-")
}

// parseListValues extracts values from a list expression like "us-east-1, us-west-2]".
func parseListValues(s string) []string {
	s = strings.TrimSuffix(strings.TrimSpace(s), "]")
	var values []string
	for _, v := range strings.Split(s, ",") {
		v = strings.TrimSpace(v)
		if v != "" {
			values = append(values, v)
		}
	}
	return values
}

// splitPolicy splits a policy that exceeds scpSizeLimit into multiple SCPs,
// one per statement. If a single statement's action list is too long,
// it is chunked into multiple statements.
func splitPolicy(baseKey string, policy *IAMPolicy, refs []ControlRef) ([]CompiledSCP, error) {
	var result []CompiledSCP

	for i, stmt := range policy.Statement {
		stmts := chunkStatement(stmt)
		for j, s := range stmts {
			p := IAMPolicy{
				Version:   "2012-10-17",
				Statement: []Statement{s},
			}
			pJSON, err := json.MarshalIndent(p, "", "  ")
			if err != nil {
				return nil, err
			}
			id := fmt.Sprintf("attest-%s-%02d", baseKey, i*10+j)
			result = append(result, CompiledSCP{
				ID:          id,
				Policy:      p,
				PolicyJSON:  string(pJSON),
				Controls:    refs,
				Description: fmt.Sprintf("Split from attest-%s (statement %s, chunk %d)", baseKey, s.Sid, j),
			})
		}
	}
	return result, nil
}

// chunkStatement splits a statement with many actions into multiple statements
// each with at most maxActionsPerStatement actions.
func chunkStatement(stmt Statement) []Statement {
	if len(stmt.Action) <= maxActionsPerStatement {
		return []Statement{stmt}
	}
	var chunks []Statement
	for i := 0; i < len(stmt.Action); i += maxActionsPerStatement {
		end := i + maxActionsPerStatement
		if end > len(stmt.Action) {
			end = len(stmt.Action)
		}
		s := Statement{
			Sid:       fmt.Sprintf("%s-%02d", stmt.Sid, i/maxActionsPerStatement),
			Effect:    stmt.Effect,
			Action:    stmt.Action[i:end],
			Resource:  stmt.Resource,
			Condition: stmt.Condition,
		}
		chunks = append(chunks, s)
	}
	return chunks
}
