// Package cedar compiles framework controls into Cedar policies for
// runtime operational enforcement. While SCPs provide structural boundaries,
// Cedar policies evaluate context-dependent conditions at decision time:
// data classification, destination attributes, temporal constraints, and
// principal qualifications.
package cedar

import (
	"fmt"
	"strings"

	"github.com/scttfrdmn/attest/internal/framework"
	"github.com/scttfrdmn/attest/pkg/schema"
)

// CompiledCedarPolicy pairs a generated Cedar policy with crosswalk metadata.
type CompiledCedarPolicy struct {
	ID          string
	PolicyText  string       // Cedar policy language
	Entities    EntitySchema // Cedar entity types and attributes
	Controls    []ControlRef
	Description string
}

// ControlRef traces a Cedar policy back to its framework control.
type ControlRef struct {
	FrameworkID string
	ControlID   string
}

// EntitySchema describes the Cedar entity types needed by a policy.
type EntitySchema struct {
	Types      []EntityType
	Actions    []ActionDef
}

// EntityType is a Cedar entity type (e.g., DataObject, Bucket, Principal).
type EntityType struct {
	Name       string
	Attributes map[string]string // attr name → type ("String", "Long", "Bool", "Set")
}

// ActionDef is a Cedar action.
type ActionDef struct {
	Name       string
	AppliesTo  []string // entity types
}

// Compiler generates Cedar policies from resolved controls.
type Compiler struct{}

func NewCompiler() *Compiler { return &Compiler{} }

// Compile generates Cedar policies from the resolved control set.
func (c *Compiler) Compile(rcs *framework.ResolvedControlSet) ([]CompiledCedarPolicy, error) {
	var policies []CompiledCedarPolicy

	for key, controls := range rcs.Controls {
		var specs []schema.OperationalEnforcement
		var refs []ControlRef
		for _, rc := range controls {
			refs = append(refs, ControlRef{
				FrameworkID: rc.FrameworkID,
				ControlID:   rc.Control.ID,
			})
			specs = append(specs, rc.Control.Operational...)
		}

		if len(specs) == 0 {
			continue
		}

		for _, spec := range specs {
			policy, entities := compileCedarSpec(spec)
			policies = append(policies, CompiledCedarPolicy{
				ID:          fmt.Sprintf("attest-%s-%s", key, spec.ID),
				PolicyText:  policy,
				Entities:    entities,
				Controls:    refs,
				Description: spec.Description,
			})
		}
	}
	return policies, nil
}

// compileCedarSpec translates an operational enforcement spec into Cedar policy text.
func compileCedarSpec(spec schema.OperationalEnforcement) (string, EntitySchema) {
	var b strings.Builder

	// Generate a forbid-unless policy. Default deny for the action,
	// with explicit permits when all attribute conditions are met.
	b.WriteString(fmt.Sprintf("// %s\n", spec.Description))
	b.WriteString(fmt.Sprintf("// Auto-generated by attest — policy %s\n\n", spec.ID))

	if spec.CedarPolicy != "" {
		// Use the hand-written Cedar policy from the framework definition.
		b.WriteString(spec.CedarPolicy)
	} else {
		// Generate from entity/attribute spec.
		b.WriteString(generateFromSpec(spec))
	}

	entities := buildEntitySchema(spec)
	return b.String(), entities
}

// generateFromSpec creates a Cedar policy from entity and attribute declarations.
func generateFromSpec(spec schema.OperationalEnforcement) string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("forbid (\n"))
	b.WriteString(fmt.Sprintf("  principal,\n"))
	b.WriteString(fmt.Sprintf("  action,\n"))
	b.WriteString(fmt.Sprintf("  resource\n"))
	b.WriteString(fmt.Sprintf(")\nunless {\n"))

	// Generate attribute conditions.
	var conditions []string
	for entity, attrs := range spec.Attributes {
		for _, attr := range attrs {
			conditions = append(conditions,
				fmt.Sprintf("  %s.%s == true", entity, attr))
		}
	}
	b.WriteString(strings.Join(conditions, " &&\n"))
	b.WriteString("\n};\n")
	return b.String()
}

func buildEntitySchema(spec schema.OperationalEnforcement) EntitySchema {
	es := EntitySchema{}
	for _, entityName := range spec.Entities {
		et := EntityType{
			Name:       entityName,
			Attributes: make(map[string]string),
		}
		if attrs, ok := spec.Attributes[entityName]; ok {
			for _, attr := range attrs {
				et.Attributes[attr] = "Bool" // default; real impl would infer type
			}
		}
		es.Types = append(es.Types, et)
	}
	return es
}
