// Package dmsp generates NIH Data Management and Security Plans (DMSP).
// Required for all NIH-funded research since January 25, 2023 (NIH DMS Policy).
// Must be submitted with grant applications, updated annually, and included in
// progress reports.
//
// The DMSP must address six elements per NIH requirements:
//  1. Types of scientific data
//  2. Tools, software, and code
//  3. Standards
//  4. Data preservation, access, and timelines
//  5. Access, distribution, or reuse considerations
//  6. Oversight of data management and sharing
//
// Attest generates the DMSP from live SRE state (environments, data classes,
// active frameworks, and attestation records), ensuring the document reflects
// actual technical controls rather than aspirational policy.
package dmsp

import (
	"fmt"
	"strings"
	"time"

	"github.com/provabl/attest/pkg/schema"
)

// Plan holds the context for generating a DMSP.
type Plan struct {
	SRE              *schema.SRE
	Crosswalk        *schema.Crosswalk
	PIName           string
	PIEmail          string
	GrantNumber      string
	InstitutionName  string
	ProjectTitle     string
	FundingICCode    string // NIH Institute/Center code, e.g., "NCI", "NIGMS"
	DataTypes        []DataType
	Repositories     []Repository
	GeneratedAt      time.Time
}

// DataType describes a category of scientific data produced by the project.
type DataType struct {
	Name            string // e.g., "Whole Genome Sequencing", "Electronic Health Records"
	Format          string // e.g., "FASTQ, VCF, BAM", "HL7 FHIR R4"
	Volume          string // e.g., "~500 GB per cohort"
	Controlled      bool   // true = controlled access (dbGaP, MUA required)
	Repository      string // where it will be deposited (e.g., "dbGaP", "GEO", "open")
	RetentionYears  int    // minimum years to retain
}

// Repository is a data repository where data will be deposited.
type Repository struct {
	Name    string // e.g., "dbGaP", "GEO", "Zenodo"
	URL     string
	Access  string // "controlled" | "open"
	NIHDesignated bool
}

// Generate produces the DMSP as a Markdown document.
func (p *Plan) Generate() (string, error) {
	if p.GeneratedAt.IsZero() {
		p.GeneratedAt = time.Now()
	}

	var b strings.Builder

	b.WriteString("# Data Management and Security Plan\n\n")
	b.WriteString(fmt.Sprintf("**Project Title**: %s\n", p.ProjectTitle))
	b.WriteString(fmt.Sprintf("**Principal Investigator**: %s (%s)\n", p.PIName, p.PIEmail))
	b.WriteString(fmt.Sprintf("**Institution**: %s\n", p.InstitutionName))
	b.WriteString(fmt.Sprintf("**NIH Grant Number**: %s\n", p.GrantNumber))
	if p.FundingICCode != "" {
		b.WriteString(fmt.Sprintf("**Funding Institute/Center**: %s\n", p.FundingICCode))
	}
	b.WriteString(fmt.Sprintf("**SRE Organization**: %s\n", p.SRE.OrgID))
	b.WriteString(fmt.Sprintf("**Generated**: %s\n", p.GeneratedAt.Format("January 2, 2006")))
	b.WriteString("\n*Generated by attest from live SRE compliance state. " +
		"All security statements are derived from deployed policy artifacts and the crosswalk manifest.*\n\n")
	b.WriteString("---\n\n")

	// Section 1: Data Types
	b.WriteString("## 1. Types of Scientific Data\n\n")
	b.WriteString("The following types of scientific data will be generated, " +
		"managed, preserved, and shared under this award:\n\n")

	if len(p.DataTypes) > 0 {
		b.WriteString("| Data Type | Format | Volume | Access | Repository |\n")
		b.WriteString("|---|---|---|---|---|\n")
		for _, dt := range p.DataTypes {
			access := "Open"
			if dt.Controlled {
				access = "Controlled"
			}
			b.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s |\n",
				dt.Name, dt.Format, dt.Volume, access, dt.Repository))
		}
		b.WriteString("\n")
	}

	// Infer data types from SRE environments
	dataClasses := collectDataClasses(p.SRE)
	if len(dataClasses) > 0 {
		b.WriteString("**Data classifications active in the SRE:**\n\n")
		for _, dc := range dataClasses {
			b.WriteString(fmt.Sprintf("- **%s**: %s\n", dc, dataClassDescription(dc)))
		}
		b.WriteString("\n")
	}
	b.WriteString("Data that cannot practicably be shared (e.g., proprietary third-party data, " +
		"data with insufficient participant consent, data with national security restrictions) " +
		"is identified in Section 5 (Access Considerations).\n\n")

	// Section 2: Tools, Software, and Code
	b.WriteString("## 2. Tools, Software, and Code\n\n")
	b.WriteString("The following tools and infrastructure are used to collect, process, " +
		"store, and share research data:\n\n")
	b.WriteString("**Cloud Infrastructure**: AWS (Amazon Web Services)\n")
	b.WriteString(fmt.Sprintf("- Organization: %s\n", p.SRE.OrgID))
	b.WriteString(fmt.Sprintf("- Environments: %d AWS accounts\n", len(p.SRE.Environments)))
	b.WriteString("- Compliance: NIST SP 800-171 Rev 2 controls deployed via attest\n")
	b.WriteString("- Encryption: AWS KMS with customer-managed keys\n")
	b.WriteString("- Access control: AWS IAM + Service Control Policies\n\n")

	b.WriteString("**Compliance Management**: attest (github.com/provabl/attest)\n")
	b.WriteString("- Automated SCP compilation and deployment\n")
	b.WriteString("- Cedar policy runtime evaluation\n")
	b.WriteString("- AWS Config continuous monitoring\n")
	b.WriteString("- Crosswalk-driven SSP and assessment generation\n\n")

	b.WriteString("**Research Compute**: Workloads specific to this project are documented " +
		"in the project's technical supplement. Container images are signed via cosign/Sigstore " +
		"and verified at deployment.\n\n")

	// Section 3: Standards
	b.WriteString("## 3. Standards\n\n")
	b.WriteString("The following standards govern data collection, documentation, " +
		"and metadata for this project:\n\n")

	b.WriteString("**Security Standards**:\n")
	// List active frameworks
	activeFrameworks := collectActiveFrameworks(p.SRE)
	for _, fw := range activeFrameworks {
		b.WriteString(fmt.Sprintf("- %s\n", fw))
	}
	b.WriteString("\n")

	b.WriteString("**Data Standards** (as applicable by data type):\n")
	b.WriteString("- Genomic data: GA4GH data standards, GFF3, VCF 4.3, FASTQ, CRAM\n")
	b.WriteString("- Clinical data: HL7 FHIR R4, OMOP CDM, SNOMED CT, LOINC\n")
	b.WriteString("- Imaging: DICOM 3.0, NIfTI\n")
	b.WriteString("- Metadata: Dublin Core, DataCite 4.5, NIH Common Data Elements (CDE)\n\n")

	// Section 4: Preservation and Timeline
	b.WriteString("## 4. Data Preservation, Access, and Associated Timelines\n\n")
	b.WriteString("**Preservation Infrastructure**:\n\n")
	b.WriteString("All research data is stored in AWS with the following durability properties:\n")
	b.WriteString("- S3 Standard: 99.999999999% durability, cross-region replication for critical datasets\n")
	b.WriteString("- EBS snapshots: daily automated backups retained per the SRE backup policy\n")
	b.WriteString("- Backup protected by SCP denying deletion of backup vaults (CP-9 / RS.7.001)\n\n")

	if len(p.Repositories) > 0 {
		b.WriteString("**Long-Term Repositories**:\n\n")
		b.WriteString("| Repository | Access | NIH-Designated | URL |\n")
		b.WriteString("|---|---|---|---|\n")
		for _, repo := range p.Repositories {
			designated := "No"
			if repo.NIHDesignated {
				designated = "**Yes**"
			}
			b.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n",
				repo.Name, repo.Access, designated, repo.URL))
		}
		b.WriteString("\n")
	}

	b.WriteString("**Retention Timeline**:\n\n")
	b.WriteString("| Data Category | Minimum Retention | Repository |\n")
	b.WriteString("|---|---|---|\n")
	for _, dt := range p.DataTypes {
		years := dt.RetentionYears
		if years == 0 {
			years = 10
		}
		b.WriteString(fmt.Sprintf("| %s | %d years post-award | %s |\n",
			dt.Name, years, dt.Repository))
	}
	if len(p.DataTypes) == 0 {
		b.WriteString("| Primary research data | 10 years post-award | As designated below |\n")
		b.WriteString("| Genomic data (controlled) | Indefinite | dbGaP |\n")
	}
	b.WriteString("\nData will be deposited to final repositories no later than the time of " +
		"associated publication or end of the performance period, whichever is earlier.\n\n")

	// Section 5: Access and Distribution
	b.WriteString("## 5. Access, Distribution, or Reuse Considerations\n\n")

	b.WriteString("**Controlled-Access Data**:\n\n")
	b.WriteString("Data generated under this award that contains personally identifiable " +
		"information, protected health information, or is subject to Certificates of " +
		"Confidentiality will be deposited to NIH-designated controlled-access repositories " +
		"(e.g., dbGaP). Access is subject to:\n\n")
	b.WriteString("- Institutional Data Use Agreement (DUA)\n")
	b.WriteString("- Data Use Certification (DUC) per NIH Genomic Data Sharing Policy\n")
	b.WriteString("- NIST SP 800-171 compliance attestation by requesting PI and institution\n")
	b.WriteString("- Annual renewal of Data Use Certification\n\n")

	b.WriteString("**Open-Access Data**:\n\n")
	b.WriteString("Data that does not contain individually identifiable information will be " +
		"deposited to appropriate NIH-designated open-access repositories and made available " +
		"under Creative Commons CC BY 4.0 license or equivalent.\n\n")

	b.WriteString("**Factors Limiting Sharing**:\n\n")
	b.WriteString("The following categories of data from this project may not be shared:\n")
	b.WriteString("- Data from participants who did not consent to broad sharing\n")
	b.WriteString("- Data subject to third-party proprietary restrictions\n")
	b.WriteString("- Pending publications (embargo period not to exceed 12 months)\n\n")

	// Section 6: Oversight
	b.WriteString("## 6. Oversight of Data Management and Sharing\n\n")
	b.WriteString(fmt.Sprintf("**Principal Investigator**: %s is responsible for all aspects "+
		"of data management under this award.\n\n", p.PIName))
	b.WriteString(fmt.Sprintf("**Institution**: %s provides institutional oversight through "+
		"the Office of Sponsored Research and institutional data governance program.\n\n",
		p.InstitutionName))

	b.WriteString("**Technical Oversight**:\n\n")
	b.WriteString("Security and compliance controls are managed via attest with the following oversight:\n\n")

	// Posture summary from crosswalk
	enforced, partial, gaps := 0, 0, 0
	for _, e := range p.Crosswalk.Entries {
		switch e.Status {
		case "enforced", "aws_covered":
			enforced++
		case "partial":
			partial++
		case "gap":
			gaps++
		}
	}
	total := enforced + partial + gaps
	if total > 0 {
		pct := float64(enforced) * 100 / float64(total)
		b.WriteString(fmt.Sprintf("- NIST 800-171 posture: **%d/%d controls enforced (%.1f%%)**\n",
			enforced, total, pct))
		if gaps > 0 {
			b.WriteString(fmt.Sprintf("- Open gaps: %d controls (tracked in POA&M)\n", gaps))
		}
	}
	b.WriteString("- Continuous monitoring: AWS Config with attest-managed conformance rules\n")
	b.WriteString("- Annual self-assessment: completed and SPRS score submitted as required\n")
	b.WriteString("- Audit trail: all policy changes committed to `.attest/` git store\n\n")

	b.WriteString("**Annual Review**: This DMSP will be reviewed and updated:\n")
	b.WriteString("- At each annual NIH progress report\n")
	b.WriteString("- Upon significant changes to the research scope or data types\n")
	b.WriteString("- When the SRE compliance posture changes materially\n\n")

	// Section 7: Security Attestation
	b.WriteString("---\n\n")
	b.WriteString("## 7. Security and Compliance Attestation\n\n")
	b.WriteString("*This section documents the technical compliance state of the SRE at time of generation. " +
		"It is auto-generated by attest and may be included in DUC submissions.*\n\n")

	b.WriteString(fmt.Sprintf("**Attestation Date**: %s\n", p.GeneratedAt.Format("2006-01-02")))
	b.WriteString(fmt.Sprintf("**SRE Organization**: %s\n", p.SRE.OrgID))
	b.WriteString(fmt.Sprintf("**Crosswalk Generated**: %s\n\n",
		p.Crosswalk.GeneratedAt.Format("2006-01-02T15:04:05Z")))

	b.WriteString("The Principal Investigator and Institutional Signing Official attest that:\n\n")
	b.WriteString("1. The institution has implemented NIST SP 800-171 Rev 2 security requirements\n")
	b.WriteString("2. A System Security Plan (SSP) documents the implementation\n")
	b.WriteString("3. A Plan of Action and Milestones (POA&M) addresses any open gaps\n")
	b.WriteString("4. Access to controlled-access NIH data is limited to personnel covered by active DUC\n")
	b.WriteString("5. Cybersecurity incidents affecting NIH data will be reported within 1 hour\n\n")

	b.WriteString("**PI Signature**: _________________________________  Date: ____________\n\n")
	b.WriteString("**Institutional Signing Official**: _____________________________  Date: ____________\n\n")
	b.WriteString("*Generate updated SSP: `attest generate ssp --framework nist-800-171-r2`*\n")
	b.WriteString("*Generate POA&M: `attest generate poam`*\n")
	b.WriteString("*Generate SPRS score: `attest generate sprs --level 2`*\n")

	return b.String(), nil
}

func collectDataClasses(sre *schema.SRE) []string {
	seen := make(map[string]bool)
	var result []string
	for _, env := range sre.Environments {
		for _, dc := range env.DataClasses {
			if !seen[dc] {
				seen[dc] = true
				result = append(result, dc)
			}
		}
	}
	return result
}

func dataClassDescription(dc string) string {
	switch strings.ToUpper(dc) {
	case "PHI":
		return "Protected Health Information — requires HIPAA safeguards and NIH Certificates of Confidentiality"
	case "CUI":
		return "Controlled Unclassified Information — requires NIST SP 800-171 / CMMC compliance"
	case "GENOMIC", "GENOME":
		return "Genomic/phenotypic data — requires dbGaP DUC and NIH Genomic Data Sharing Policy compliance"
	case "FERPA":
		return "Educational records — protected under FERPA; limited sharing without consent"
	case "PII":
		return "Personally Identifiable Information — requires access controls and breach notification procedures"
	case "OPEN":
		return "Non-sensitive research data — eligible for open access deposit"
	default:
		return dc
	}
}

func collectActiveFrameworks(sre *schema.SRE) []string {
	var frameworks []string
	for _, fw := range sre.Frameworks {
		switch fw.ID {
		case "nist-800-171-r2":
			frameworks = append(frameworks, "NIST SP 800-171 Rev 2 (CMMC Level 2 baseline)")
		case "hipaa":
			frameworks = append(frameworks, "HIPAA Security Rule (PHI protection)")
		case "fedramp-moderate":
			frameworks = append(frameworks, "FedRAMP Moderate Baseline (cloud security)")
		case "nih-research-security":
			frameworks = append(frameworks, "NIH Research Security Program (NOT-OD-26-017)")
		case "ferpa":
			frameworks = append(frameworks, "FERPA (student educational records)")
		default:
			frameworks = append(frameworks, fw.ID)
		}
	}
	if len(frameworks) == 0 {
		frameworks = append(frameworks, "NIST SP 800-171 Rev 2 (to be activated — run `attest frameworks add nist-800-171-r2`)")
	}
	return frameworks
}
